include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    - avoid_classes_with_only_static_members
    - avoid_types_on_closure_parameters
    - cancel_subscriptions
    - unnecessary_null_aware_operator_on_extension_on_nullable

analyzer:
  errors:
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    public_member_api_docs: ignore
    no_default_cases: ignore

    # Style decisions
    always_put_required_named_parameters_first: ignore
    always_use_package_imports: ignore
    sort_constructors_first: ignore
