name: hauptwerk_hub
description: "Hauptwerk Hub"
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
